DROP TABLE PRODUCTOS


CREATE TABLE PRODUCTOS(
	ID INTEGER PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	PRECIO DECIMAL(10,2) NOT NULL,
	STOCK INTEGER NOT NULL,
	ESTADO VARCHAR(1)
);

CREATE TABLE USUARIOS(
	ID_USUARIO INTEGER PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	CODIGO_USUARIO VARCHAR(200) NOT NULL,
	CONTRASENIA VARCHAR(100) NOT NULL,
	ESTADO VARCHAR(1) NOT NULL
);