DROP TABLE PRODUCTOS


CREATE TABLE PRODUCTOS(
	ID INTEGER PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	PRECIO DECIMAL(10,2) NOT NULL,
	STOCK INTEGER NOT NULL,
	ESTADO VARCHAR(1)
);

CREATE TABLE USUARIOS(
	ID_USUARIO INTEGER PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(100) NOT NULL,
	CODIGO_USUARIO VARCHAR(200) NOT NULL,
	CONTRASENIA VARCHAR(100) NOT NULL,
	ESTADO VARCHAR(1) NOT NULL
);

CREATE TABLE CAB_FACT(
	ID_FACTURA INTEGER PRIMARY KEY IDENTITY(1,1),
	NOMBRE_CLIENTE VARCHAR(100) NOT NULL,
	IDENTIFICACION VARCHAR(20) NOT NULL,
	TELEFONO VARCHAR(20),
	EMAIL VARCHAR(100),
	FECHA DATETIME DEFAULT GETDATE(),
	ID_USUARIO INTEGER,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE DET_FACT(
	ID_DET_FACT INTEGER PRIMARY KEY IDENTITY(1,1),
	ID_FACTURA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD INTEGER NOT NULL,
	PRECIO_UNI DECIMAL(10, 2) NOT NULL,
	SUB_TOTAL DECIMAL(10, 2) NOT NULL,
	IVA AS (ROUND((CANTIDAD * PRECIO_UNI) *0.15, 2)) PERSISTED,
	TOTAL_SIN_IVA AS (CANTIDAD * PRECIO_UNI) PERSISTED,
	TOTAL AS (CANTIDAD * PRECIO_UNI) PERSISTED,
	FOREIGN KEY (ID_FACTURA) REFERENCES CAB_FACT(ID_FACTURA),
	FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID)
);
